export const USERSIGNUPREQ = "USERSIGNUPREQ";
export const USERSIGNUPRES = "USERSIGNUPRES";
export const USERSIGNUPREJ = "USERSIGNUPREJ";

export const USERSIGNINREQ = "USERSIGNINREQ";
export const USERSIGNINRES = "USERSIGNINRES";
export const USERSIGNINREJ = "USERSIGNINREJ";

export const USERSIGNOUTREQ = "USERSIGNOUTREQ";
export const USERSIGNOUTRES = "USERSIGNOUTRES";
export const USERSIGNOUTREJ = "USERSIGNOUTREJ";

export const USERPOPUPSIGNINREQ = "USERPOPUPSIGNINREQ";
export const USERPOPUPSIGNINRES = "USERPOPUPSIGNINRES";
export const USERPOPUPSIGNINREJ = "USERPOPUPSIGNINREJ";

// Product CRUD

export const ADDDATAREQ = "ADDDATAREQ";
export const ADDDATARES = "ADDDATARES";
export const ADDDATAREJ = "ADDDATAREJ";

export const SINGLEDATAREQ = 'SINGLEDATAREQ';
export const SINGLEDATARES = 'SINGLEDATARES';
export const SINGLEDATAREJ = 'SINGLEDATAREJ';

export const EDITDATAREQ = "EDITDATAREQ";
export const EDITDATAREJ = "EDITDATAREj";

export const DELETEDATAREQ = "DELETEDATAREQ";
export const DELETEDATAREJ = "DELETEDATAREJ";

export const ADDTOCARTREQ = 'ADDTOCARTREQ';
export const ADDTOCARTRES = 'ADDTOCARTRES';
export const ADDTOCARTREJ = 'ADDTOCARTREJ';